baseURL = 'https://drittaatokyo.com/'
languageCode = 'it-IT'
defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []
title = 'Dritta a Tokyo'

[markup.highlight]
noclasses = false
style = "github"


[[module.imports]]
path = "github.com/willfaught/paige"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.paige.pages]
disable_authors = false
disable_date = false
disable_keywords = false
disable_next = false
disable_prev = false
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true
disable_title = true


[params.paige.subpages]
disable_authors = false
disable_date = false
disable_keywords = false
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[params.paige.site]
disable_breadcrumbs = true
disable_menu = false
color = "#0d6efd" # Bootstrap primary color and theme color for Safari and Windows
color_scheme = "auto" #it can be only auto dark or light
menu_style = "underline" # Must be "links", "pills", "tabs", or "underline"
