baseURL = 'https://drittaatokyo.com/'
languageCode = 'it-IT'
title = 'Dritta a Tokyo'

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
